### ISSUE TITLE
How to save Login Credentials

### ISSUE THREAD

**Issue by kilyan-s** [appcelerator-modules/titanium-identity#10]
Hi, 

First, thanks for this module it works great and it is easy to use. 

I'm using this module in a project, I want to save the user's credentials (email & password) in a keychain then use Touch ID or Face ID to login on the app. 

I am now using a keychain to save the user's password, but how would you suggest saving the email used for login ? Is it possible to save both email & password in the same keychain ? 

Best regards 
Kilyan

**Comment by hansemannn** [comment]
Only security related information should be stored in the keychain. For non-sensitive data, use either `Ti.App.Properties.setString('email', your_email)` or [`Ti.App.iOS.UserDefaults`](http://docs.appcelerator.com/platform/latest/#!/api/Titanium.App.iOS.UserDefaults).

**Comment by kilyan-s** [comment]
Sorry I thought we could store both login et password in the keychain.

Thanks for your help,
Kilyan

**Comment by hansemannn** [comment]
Sure, you can. You just need to use different identifiers.
