### ISSUE TITLE
Crash iphone x Face id 

### ISSUE THREAD

**Issue by amigoni** [appcelerator-modules/titanium-identity#21]
I'm getting a hard crash on calling authenticate() for iphone x or face id. Works find on touch id.
Titanium 7.4.1 ios 12

**Comment by hansemannn** [comment]
Please read [the docs](https://docs.appcelerator.com/platform/latest/#!/api/Modules.Identity) carefully, paragraph `Face ID Requirements (iOS only)`:

> For Face ID to work properly, you need to add a <key> item to the <plist> element of your tiapp.xml file:

```xml
<ti:app>
  ...
  <ios>
    ...
    <plist>
      <dict>
        <key>NSFaceIDUsageDescription</key>
        <string>Why you need Face ID.</string>
      </dict>
    </plist>
    ...
  </ios>
  ...
</ti:app>
```

**Comment by amigoni** [comment]
Thanks Hans. That worked. My bad.
