### ISSUE TITLE
Fails on Android 10

### ISSUE THREAD

**Issue by grebulon** [appcelerator-modules/titanium-identity#37]
FingerprintHeper#initCipher() fails. Log shows:
```
E/KeyStore: generateKeyInternal failed on response 2
E/FingerPrintHelper: (KrollRuntimeThread) [16,15974] Unable to initialize cipher
```
This happened to me with Pixel 2 (google walleye) on Android 10 (API 29)

Probably needs to migrate to BiometricPrompt and BiometricManager.

**Comment by garymathews** [comment]
Fixed in `3.0.0`
