### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by Claymm** [appcelerator-modules/titanium-identity#5]
Would be good to get some instructions either [here](https://github.com/appcelerator-modules/titanium-identity/blob/master/README.md) or on the official [Axway Appcelerator documentation](http://docs.appcelerator.com/platform/latest/#!/api/Modules.Identity) around how to install the native module.

It wasn't very clear this was not part of the SDK and I had to download and install manually the release from [there](https://github.com/appcelerator-modules/titanium-identity/releases).

**Comment by hansemannn** [comment]
It will be prepackaged in 7.0.0+, but thanks for the hint. It's generally as any other module and includes example-files for each platform. Feel free to improve the documentation 🙂.
