### ISSUE TITLE
Consecutive Tries Fail on Android

### ISSUE THREAD

**Issue by jwogan5** [appcelerator-modules/titanium-identity#55]
Using Android I can "authenticate" and it works the first time.  If you then log out of the app but don't close it and then try to log right back into the app the authenticate method will then keep returning "{"error":"Failed to encrypt the data with the generated key.","success":false}". 

It seems once you log in the first time all calls to authenticate just end up calling tryEncrypt.  I tried to call invalidate in hopes that it would clear the fingerprint session but it doesn't.  

Any idea on an approach to this that will allow the user to re-login if the already have the fingerprint session already authenticated.

**Comment by rushisaband** [comment]
I'm having this exact same issue.  Using SDK 9.3.2. Running Android 11, targeting API Level 30.   Can't find any workaround.
