### ISSUE TITLE
Android : Failed to encrypt the data with the generated key

### ISSUE THREAD

**Issue by azamouchi** [appcelerator-modules/titanium-identity#9]
Config : 
- Android : 6.0
- Device : https://www.gsmarena.com/wiko_u_feel_lite-8204.php
- Titanium SDK : 7.0.1
- Module Version : 2.0.0 & 2.0.1

Hi,
I've tried the module on a simple android app, just to see how it works.
After an authentification attempt with a fingerprint, i get this error message every time

```{"error":"Failed to encrypt the data with the generated key.","success":false}```

The fingerprint is correctly configured and it can be used to unlock the device, but does not work on the app. Is there anything i'm missing or it's a module issue ?

[testTouchId.zip](https://github.com/appcelerator-modules/titanium-identity/files/1672887/testTouchId.zip)

Thank you.

**Comment by hansemannn** [comment]
Hey there! Can you please open a ticket on [JIRA](https://jira.appcelerator.com)? That's the central place for our bug-tracking and will have better attention to be addressed. Thanks!
